# Generated by Django 2.1.2 on 2020-05-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200430_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_url',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_url',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
