# Generated by Django 2.1.2 on 2020-05-02 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.UserRole'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user_role',
            field=models.TextField(max_length=400),
        ),
    ]
