# Generated by Django 2.1.2 on 2020-04-30 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200430_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedcontenttype', models.CharField(choices=[('YT', 'Youtube'), ('FB', 'Facebook'), ('IG', 'Instagram'), ('NONE', 'NONE')], default='NONE', max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_connected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='embedcontenttype_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.EmbedContentType'),
        ),
    ]
