# Generated by Django 2.1.2 on 2020-04-30 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200430_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='embed_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='embedcontenttype',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_connected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
