# Generated by Django 2.1.2 on 2020-05-06 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200506_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditaquisition',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('D', 'Denied')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_connected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
