# Generated by Django 2.1.2 on 2020-05-07 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20200507_0450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentitem',
            old_name='user',
            new_name='contentcreator',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_connected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
